[build.environment]
  NODE_VERSION = "14"

[build]
  command = "yarn build && next export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200